name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - .changeset/**
      - .github/workflows/release.yml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        cache: yarn
    - run: yarn install
    - run: yarn build
    - uses: changesets/action@v1
      with:
        publish: yarn changeset publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
